# Site Settings 
description              : &description "personal website"
url                      : https://janellecheung.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" 

# Biographic information
author:
  avatar           : "Headshoot.png"
  name             : "Janelle"
  location         : "Canada"
  email            : "janelle.cheung@alumi.ubc.ca" 


markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
