# Site Seetings 
title: Janelle Cheung
logo: /assets/Headshoot.png

description              : &description "personal website"
url                      : https://janellecheung.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" 


markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
